[[main]]
    identifier = "about"
    name = "About"
    url = "/"
    weight = 1

[[main]]
    identifier = "writing"
    name = "Writing"
    url = "/writing"
    weight = 2
    
# Social Media Configuration

[[social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/saurabh3460"
    weight = 1

[[social]]
    identifier = "twitter"
    name = "Twitter"
    url = "https://x.com/saurabh3460"
    weight = 2

[[social]]
    identifier = "linkedin"
    name = "Linkedin"
    url = "https://www.linkedin.com/in/saurabh-y-311635114/"
    weight = 3

